window.KD_PRODUCTS=[
{id:"kolekcija-kumovi-01",name:"Kolekcija „Poslednji preživeli“",category:"Gotove ideje",desc:"Vaše fotografije na majicama — da svi odmah znaju ko je kriv za ovo okupljanje.",image:"assets/images/kolekcija-kumovi-01.png",colors:["Crna"],sizes:["S","M","L","XL","XXL"],positions:["Napred"],price:"TRI PRASETA GROK"},
{id:"majica",name:"Majica",category:"Tekstil",desc:"Uniforma ekipe i dokaz da ste svi pristali na istu glupost.",image:"assets/images/majica-bela-transparent.png",colors:["Crna","Bela","Plava","Crvena"],sizes:["S","M","L","XL","XXL"],positions:["Napred","Leđa","Rukav"],price:"TRI PRASETA GROK"},
{id:"tasos",name:"Peškir",category:"Letnji program",desc:"Za plažu, bazen i brisanje tragova sinoćnjih odluka.",image:"assets/images/peskir-plava.png",colorImages:{"Plava":"assets/images/peskir-plava.png","Crvena":"assets/images/peskir-crvena.png","Zelena":"assets/images/peskir-zelena.png","Bež":"assets/images/peskir-bez.png","Siva":"assets/images/peskir-siva.png"},colors:["Plava","Crvena","Zelena","Bež","Siva"],sizes:[],positions:["Donji ugao","Sredina"],price:"TRI PRASETA GROK"},
{id:"pigna-maxi",name:"Krigla",category:"Čaše i šolje",desc:"Za zdravice koje počnu kulturno, a završe kao interna fora.",image:"https://apiv2.promosolution.services/content/ModelItem/4418591_001.webp?v=260713154432",colors:["Transparentna"],sizes:[],positions:["Prednja strana"],price:"TRI PRASETA GROK"},
{id:"calabria",name:"Torba",category:"Torbe",desc:"Sve staje unutra — osim odgovornosti.",image:"assets/images/torba-crna.png",colorImages:{"Crna":"assets/images/torba-crna.png","Bela":"assets/images/torba-bela.png","Plava":"assets/images/torba-plava.png","Crvena":"assets/images/torba-crvena.png","Zelena":"assets/images/torba-zelena.png","Žuta":"assets/images/torba-zuta.png","Narandžasta":"assets/images/torba-narandzasta.png"},colors:["Crna","Bela","Plava","Crvena","Zelena","Žuta","Narandžasta"],sizes:[],positions:["Prednja strana"],price:"TRI PRASETA GROK"},
{id:"arlo",name:"Kačket",category:"Tekstil",desc:"Čuva glavu od sunca, ali ne i od loših ideja.",image:"assets/images/kacket-crna.png",colorImages:{"Crna":"assets/images/kacket-crna.png","Bela":"assets/images/kacket-bela.png","Plava":"assets/images/kacket-plava.png","Crvena":"assets/images/kacket-crvena.png","Zelena":"assets/images/kacket-zelena.png","Bež":"assets/images/kacket-bez.png","Siva":"assets/images/kacket-siva.png"},colors:["Crna","Bela","Plava","Crvena","Zelena","Bež","Siva"],sizes:[],positions:["Napred","Sa strane"],price:"TRI PRASETA GROK"},
{id:"sonder",name:"Otvarač",category:"Dodaci",desc:"Mali predmet sa najvećom odgovornošću u ekipi.",image:"assets/images/otvarac-crna.png",colorImages:{"Crna":"assets/images/otvarac-crna.png","Bela":"assets/images/otvarac-bela.png","Plava":"assets/images/otvarac-plava.png","Crvena":"assets/images/otvarac-crvena.png"},colors:["Crna","Bela","Plava","Crvena"],sizes:[],positions:["Prednja strana"],price:"TRI PRASETA GROK"},
{id:"adler",name:"Boca",category:"Piće",desc:"Hidratacija za one koji se sete na vreme.",image:"assets/images/boca-maslinasta.png",colorImages:{"Maslinasta":"assets/images/boca-maslinasta.png","Plava":"assets/images/boca-plava.png","Bela":"assets/images/boca-bela.png","Crna":"assets/images/boca-crna.png"},colors:["Maslinasta","Plava","Bela","Crna"],sizes:[],positions:["Prednja strana"],price:"TRI PRASETA GROK"},
{id:"rashladna-torba",name:"Rashladna torba",category:"Letnji program",desc:"Piće ostaje hladno čak i kad se ekipa usija.",image:"assets/images/rashladna-torba.png",colors:["Crna"],sizes:[],positions:["Prednja strana"],price:"TRI PRASETA GROK"}
];

window.KD_PACKAGES=[
{id:"osnovni",name:"Osnovni debili",kicker:"Za kratko i jako",items:["Majica","Kačket","Otvarač"]},
{id:"morski",name:"Morski debili",kicker:"Letnji paket",items:["Majica","Peškir","Rashladna torba","Boca"]},
{id:"kompletni",name:"Kompletni debili",kicker:"Bez polovičnih mera",items:["Majica","Peškir","Kačket","Krigla","Torba","Otvarač","Boca"]}
];
